# BASE UI
ColorColumn: '- starnight'
Conceal: 'steel starnight'
Cursor: 'mistbloom starnight'
CursorIM: '@Cursor'
CursorColumn: '- starnight'
CursorLine: '- starnight_l'
CursorLineNr: 'celestialblue starnight'
Directory: 'mistbloom'
DiffAdd: 'alice_l alice_d'
DiffChange: 'alicia_l alicia_d'
DiffDelete: 'akari_l akari_d'
DiffText: 'alicia_l alicia_d'
ErrorMsg: 'bocolo'
VertSplit: 'steel_d starnight'
WinSeparator: '@VertSplit'
Folded: 'mistbloom_d starnight'
FoldColumn: 'mistbloom_d starnight'
SignColumn: 'mistbloom_d starnight'
IncSearch: '- - r'
LineNr: 'aquamarina starnight'
LineNrAbove: 'aquamarina starnight'
LineNrBelow: 'aquamarina starnight'
MatchParen: 'starnight_l starnight'
ModeMsg: 'mistbloom_d'
MoreMsg: 'mistbloom_d'
NonText: 'starnight_l'
Normal: 'mistbloom starnight'
NormalFloat: 'mistbloom starnight'
FloatBorder: '@Normal'
PMenu: 'mistbloom aika_d'
PMenuSel: 'mistbloom aika b'
PmenuSbar: 'mistbloom_d aika_d'
PmenuThumb: 'mistbloom mistbloom'
Question: 'alice'
QuickFixLine: '- starnight_l'
Search: 'starnight_l akari'
CurSearch: 'starnight_l alicia'
SpecialKey: 'starnight_l'
SpellBad: 'bocolo'
SpellLocal: 'mistbloom'
SpellCap: 'mistbloom'
SpellRare: 'mistbloom'
StatusLine: 'mistbloom_d starnight_l'
StatusLineNC: 'mistbloom_d starnight_d'
TabLine: 'steel_d starnight_d'
TabLineFill: 'steel_d starnight_d'
TabLineSel: 'mistbloom starnight'
Title: 'aquamarina'
Visual: '- starnight_l'
VisualNOS: '@VisualNOS'
WarningMsg: 'bocolo'
WildMenu: 'starnight mistbloom_d'
# BASE SYNTAX
Comment: 'steel - i'
Constant: 'aquamarina'
String: 'mistbloom_d' # Constant
Character: '' # Constant
Boolean: '' # Constant
Number: '' # Constant
Float: '' # Constant
Identifier: 'mistbloom'
Function: 'celestialblue' # Identifier
Statement: 'aria'
Conditional: '' # Statement
Repeat: '' # Statement
Label: '' # Statement
Operator: 'mistbloom' # Statement
Keyword: '' # Statement
Exception: '' # Statement
PreProc: 'aria'
Include: '' # PreProc
Define: '' # PreProc
Macro: '' # PreProc
PreCondit: '' # PreProc
Type: 'celestialblue'
StorageClass: '' # Type
Structure: '' # Type
Typedef: '' # Type
Special: 'mistbloom'
SpecialChar: '' # Special
Tag: 'aria' # Special
Delimiter: '' # Special
SpecialComment: '' # Special
Debug: '' # Special
Underlined: 'mistbloom_d - u'
Ignore: '-'
Error: 'bocolo'
Todo: 'alice -'
